services:
  dbc:
    build:
      context: dbc/
    environment:
      POSTGRES_PASSWORD: rootpass
    ports:
      - 12321:5432
  springchan:
    build:
      context: springchan/
    ports:
      - 12322:8080

  web:
    build:
      context: web/
    ports:
      - 80:80
